### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by bilbof** [armin-pfaeffle/sass-autocompile#4]
Hey Armin, this is probably just a usage error but I was wondering if you knew what's causing this error?

I've installed node.js and installed node-sass globally, but with this code:

`// out: main.css, compress: true`

I'm seeing this:

"error while compiling.

"Error: command failed: /bin/sh: node-sass: command not found"

Does this mean I haven't installed node-sass properly?

When I try from the terminal I'm seeing:

"Provide a Sass file to render

  Example
    node-sass --output-style compressed foobar.scss foobar.css
    cat foobar.scss | node-sass --output-style compressed > foobar.css
"

Any thoughts? Thanks :)

**Comment by armin-pfaeffle** [comment]
Well, perhaps the execution call in my code only works on Windows systems. I have to test it on a Linux OS. I will answer your comment soon!

**Comment by armin-pfaeffle** [comment]
What OS do you use? Linux or a Mac OS?

I installed Linux Mint (64-bit) and tried the plugin. Everthing worked fine after installing npm and node-sass (global installation with parameter -g).

Please help me to find the difference?! :)

**Comment by bilbof** [comment]
Hey Armin, sorry I didn't see the notification for this! Thanks for replying.

I'm using a Mac OS. I got the the compile working in terminal with 'node-sass main.scss style.css', so node-sass is definitely installed properly. Auto-compile is throwing the same error. Any known bugs with Mac OS? :)

**Comment by armin-pfaeffle** [comment]
Here a simple, but not satisfying solution for your problem: Try to start atom from terminal by changing to corresponding directory and enter `atom`command.

When you are interessted in this problem, have a look at [this thread](https://discuss.atom.io/t/how-to-execute-node-js-child-process-from-package/4880).

I'm working on a solution.

**Comment by armin-pfaeffle** [comment]
Please try newest version 0.6.0. and tell me if it helps you?!

I implemented a small fix for Mac OS. This fix adds path `/usr/local/bin` to `$PATH` variable if not already there, so shell can find `node-sass` command. Modified path is restored after calling `node-sass` command.

**Comment by bilbof** [comment]
Hey I installed the 0.6.0 version, still getting same error. "bin/sh: node-sass: command not found"

**Comment by armin-pfaeffle** [comment]
Hm... Can you answer me following questions:
- Which version of Mac OS do you use?
- How do you start Atom? Via Dock? Via terminal?
- Can you please check path `/usr/local/bin`. Is there an executable called `node-sass`?

**Comment by bilbof** [comment]
OS X Yosemite 10.10.2

I open Atom via the application / dock

yep, node-sass is there.

**Comment by armin-pfaeffle** [comment]
Thanks for your information! It's a lil bit strange that I cannot reproduce your problem...

Now I replaced my first fix attempt with an "absolute path" fix. On Mac OS platforms `node-sass` is executed via absolute path. Therefore I added a new option to *sass-autocompile* so users can edit it -- the default value is `/usr/local/bin`.

Please try version 0.6.1 and tell me if it works now!? Thanks :)

**Comment by bilbof** [comment]
It worked! :+1: 

Thanks for your help, this will save me so much time. I hate css! :)

**Comment by armin-pfaeffle** [comment]
Great to hear! :)

But I do not understand why my first solution did not work...

**Comment by bilbof** [comment]
It was probably me messing something up... :monkey:

**Comment by armin-pfaeffle** [comment]
Hm, I don't think so. But I cannot find the the right answer why I has not worked... The problem was that the shell, used by Dock, does not look in `/usr/local/bin` for commands, so my first fix added this path to the `$PATH` variable. After calling `node-sass` command this path has been removed from `$PATH`. So `node-sass` should be actually found!

But hey... It's working now ;) And it's a simpler and bit more flexible fix!

**Comment by bilbof** [comment]
Lol sorry I mean 'I was messing up...'!

**Comment by plumdumpling** [comment]
Hey Armin,
unfortunately I get the same error in version 0.6.3 on OS X Yosemite 10.10.3.
Maybe you can help me, too!?
Thanks!

**Comment by armin-pfaeffle** [comment]
Yes, I think we can get it work for you! ;)

- Is `node-sass` command working in terminal? If not, you have to install [node.js](https://nodejs.org/) and then node-sass (via terminal: `npm install node-sass -g`).
- Can you check where `node-sass` executable is placed? Probably not in `/usr/local/bin`? You can use `which node-sass` command in terminal to check the path! If path is **not** `/usr/local/bin`, put the visible path to the option **Path to node-sass-command**. (it's the last option)

Did this help you?

**Comment by plumdumpling** [comment]
Thanks for your reply!
The `node-sass` command is working in terminal.
The node-sass executable is placed in `/usr/local/bin`. The node-sass file in `/usr/local/bin` linked to `/usr/local/lib/node_modules/node-sass/bin` so I tried this path as path to node-sass, but didn't work either. :(
Do you have any further suggestions?

**Comment by armin-pfaeffle** [comment]
Well... I'm a lil bit helpless :-/

The only thing, I could imagine, is that `if process.platform is "darwin"` is false on your system. But I don't know why this should be the case. Because else the given path (or its default value) and `node-sass` command ist combined to an absolute path e.g. `/usr/local/bin/node-sass` and this executable exists on your system.

Can you open the **Developer Tools** (View → Developer → Toggle Developer Tools) and run `process.platform` in Console? What string is printed there then?

**Comment by plumdumpling** [comment]
`process.platform` is "darwin"

**Comment by armin-pfaeffle** [comment]
Okay... Then I have no idea what's wrong then!? Perhaps the execution string is wrong... But it's only a guess. Can you try to create a SCSS file at a path with no spaces and so special chars? Does it compile? Do you have any special characters in your working directory?

Another thing you can try is to output the `execString` variable in `sass-autocompile-view.coffee`. Therefore open this file `/Users/<username>/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee` and modified [line 172](https://github.com/armin-pfaeffle/sass-autocompile/blob/master/lib/sass-autocompile-view.coffee#L172) from:
```
execString = @buildExecString params
```
to:
```
execString = @buildExecString params
console.log execString
```
After that **reload** Atom (View → Reload), so the changes are applied, open **Developer Tools**, go to **Console** and try to compile a SCSS file. Then you see the content of **execString**. Please post it!

**Comment by plumdumpling** [comment]
I made sure that there are no spaces or special characters in the path.

execString is `/usr/local/bin/node-sass --output-style nested "path-to-scss-file" "path-to-css-file"`

**Comment by armin-pfaeffle** [comment]
Now I'm completely out of ideas... :( Do you have the latest node.js version and latest Atom version installed? Can there any problem with 32 and 64 bit processes?

The only thing I can offer is to debug my package direct on your Mac, when you allow. For this contact me via mail@armin-pfaeffle.de.

**Comment by plumdumpling** [comment]
I have the latest versions of both Node.js and Atom.
Debugging on my Mac would be great, thank you! I'll contact you... :)

**Comment by armin-pfaeffle** [comment]
So... We solved the problem now! It was a corrupt node-sass installation. Everything is fine with `sass-autocompile` ;)

**Comment by plumdumpling** [comment]
Finally after Armin spent a lot of time with my Mac (thank you for that :)) he found the problem.
For everybody who has the same issue on its Mac, just start Atom via terminal instead of the icon in the dock and it will work fine.

**Comment by wielski** [comment]
I have the same problem.
From Atom runned by terminal everything works fine, but i want to run it from dock (opening terminal every time when I want run Atom little not comfortable).

**Comment by armin-pfaeffle** [comment]
Hey!

I do not exactly know what I have done at that time. I think, I removed node-sass via `npm uninstall node-sass -g` and reinstalled it via `npm install node-sass -g` -- it's important to use the `-g` parameter so node-sass command is callable via shell. After that everything worked.

Perhaps you can try to compile a SCSS file via shell and see if that works? E.g. `node-sass input.scss ouput.css`

**Comment by wielski** [comment]
I restarted my mac, and everything is working now. Magic? Maybe...
But solution was simple :) Thank you, plugin is perfect.

**Comment by armin-pfaeffle** [comment]
Well... That sounds great ;) Would be really interessting what the problem was...

Thanks!

**Comment by e-sushi** [comment]
Same error here on Ubuntu.

    Error: Command failed: /bin/sh -c node-sass …

Now, I have already tried to use the (let’s just call it) “Mac trick” by going to the settings page and configuring the path `/home/tec/npm/bin/` but this doesn’t fix it.

    Error: Command failed: /bin/sh -c node-sass …

This raises a question: I know it says "Mac Only", but does that practically mean you are actually filtering this setting, only reading it when detecting "Darwin", aka a Mac OS? If, you should probably get rid of that selectiveness as it might offer an option to fix things on Ubuntu too.

As for what works: starting atom from the shell. Assuming paths et al are correctly parsed, this indicates some sort of "rights" problem… especially since my Ubuntu hits the exact same wall as a Mac.

**Comment by e-sushi** [comment]
Just checked your code, and my gut feeling obviously was correct. You should at least to kill or modify your `darwin` filtering.

I changed `sass-autocompile-view.coffee` by commenting out line 228 and addapting the indents accordingly to read the node-sass path from the settings and that fixed things alltogether.

More specific, a simple change from

        # If it's Mac OS we have to add macOsNodeSassPath to command and to environment variable
        # PATH so shell AND node.js can find node-sass command
        if process.platform is "darwin"
                path = require('path')
                command = path.join(@options.macOsNodeSassPath, command)
                environment.PATH += ":#{@options.macOsNodeSassPath}"

to

        # If it's Mac OS we have to add macOsNodeSassPath to command and to environment variable
        # PATH so shell AND node.js can find node-sass command
        # if process.platform is "darwin"
        path = require('path')
        command = path.join(@options.macOsNodeSassPath, command)
        environment.PATH += ":#{@options.macOsNodeSassPath}"

and – of course – having set a path in the according settings box, lets me start atom without tthat "start from terminal" fix. 

The result produces a nice…

        Rendering Complete, saving .css file...
        Wrote Source Map to /home/tec/GithubAtom/main.css.map
        Wrote CSS to /home/tec/GithubAtom/main.css

Bingo!

In the unlikely case you really think you need to filter out that setting per operating system, at least add the following to the list (devtools output):

        process.platform
        "linux"

**Comment by e-sushi** [comment]
Had a bit of time on my side, so I wrapped up an according pull request: https://github.com/armin-pfaeffle/sass-autocompile/pull/20

**Comment by armin-pfaeffle** [comment]
Hey!

Thanks for your report! Will be fixed in next version. I think I will publish it today or at the beginning of next week.

**Comment by armin-pfaeffle** [comment]
Hey! I published a the version 0.10.0 right now. Please check the renamed option [Path to 'node-sass' command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command). This should work on every system now.

Thanks for your pull request, but I modified a lot of things, why I had no use for that.

**Comment by ChrisChiera** [comment]
Having the same issue. I'm a 5k iMac with a fresh install of 10.11 (El Capitan). 

Installed homebrew and node.js without a problem and installed atom and this plugin per your instructions.

When trying to save a .scss file it says, "/bin/sh: node-sass: command not found".

Node-sass appears to have been installed to "/usr/local/bin/node-sass" when using your instructions on GitHub. Should it be somewhere else, or is there a setting to change to get it to work at that location?

**Comment by BuiltByEdgar** [comment]
I had the same problem. With the @ChrisChiera solution, Atom had to run from the terminal to compile. I added the path to my `init.cofee` file (Init Script) and now, Atom works well when I starting it from the icon!

```javascript
process.env.PATH = ["/bin",
                    "usr/bin",
                    "usr/local/bin",
                    "usr/local/bin/node_modules/node-sass/bin",
                    ].join(":")
```
Thanks!
